#!/bin/bash

PKGVER=`dpkg-query -W -f='${Version}' nwfermi | awk -F "-" '{print $1}'`
PKGVER=${PKGVER#*:}

echo "Removing all DKMS Modules"
dkms remove -m nwfermi -v $PKGVER --all -q > /dev/null
echo "Done."
echo "Adding Module to DKMS build system"
echo "driver version= $PKGVER"
dkms add -m nwfermi -v $PKGVER > /dev/null
echo "Doing initial module build"
dkms build -m nwfermi -v $PKGVER > /dev/null
echo "Installing initial module"
dkms install -m nwfermi -v $PKGVER > /dev/null
echo "Done."
