#!/bin/bash

test -f /var/run/puppet/agent.pid && puppet resource service puppet ensure=stopped
rm -r $(puppet agent --configprint ssldir)/* && puppet agent --test
grep "START=yes" /etc/default/puppet && puppet resource service puppet ensure=running

