#!/bin/bash
#
# Esteban M. Navas Martin
# algodelinux@gmail.com
# Fecha creacion: 17/06/2015

# Requiere tener instalado el paquete facter para identificar el tipo de máquina
tipo=$(facter tipo)

if [ $tipo = "infolab" ] || [[ $tipo =~ notebook.* ]]; then

   # Borramos los directorios HOME
   rm -fr /home/profesor/* 2>/dev/null
   rm -fr /home/alumnos/* 2>/dev/null

   # Borramos las credenciales de usuario cacheadas
   for usuario in `cc_dump |awk '{print $3}' | sed '1,2d'`; do
       cc_test -update any $usuario -
   done

   # Creamos un fichero testigo para borrar homes solamente cuando no exista el fichero
   touch /etc/homecleaned
fi

