#!/bin/bash

mount -t proc proc-chroot /opt/ltsp/i386/proc
mount -t devpts devpts-chroot /opt/ltsp/i386/dev/pts
ltsp-chroot -a i386 dpkg --configure -a
ltsp-chroot -a i386 apt-get -f install
umount proc-chroot
umount devpts-chroot

